### ISSUE TITLE
Errore installazione su Ubuntu 17.04

### ISSUE THREAD

**Issue by marcomb** [italia/dati-ckan-docker#1]
Sto provando a seguire l'installazione del package Dati-Ckan-Docker su un Ubuntu 17.04.. ma non riesco a completare l'ultima compose..

Ho seguito le istruzioni.. tutto bene sino a quando (ultimo comando) lancio il comando docker-compose up -d

marco@marco-LIFEBOOK-E752:~/dati-ckan-docker$ docker-compose up -d

Pulling solr (daf-ckan-solr:1.0.0)...
Pulling repository docker.io/library/daf-ckan-solr
ERROR: Error: image library/daf-ckan-solr:1.0.0 not found

Riprovato tante volte. Suggerimenti?

**Comment by dgreco** [comment]
Sembra che non trovi l'immagine per solr, hai lanciato lo script build_local.sh? forse ha fallito provando a creare l'immagine per solr.

**Comment by piersoft** [comment]
su ubuntu 17 credo non possa andare lo stesso schema di solr, jetty non è jetty ma jetty8 ect.
io proverei su ubuntu 16

**Comment by marcomb** [comment]
Rifatto girare il build_local.sh ed ora va. Tutto a posto anche su U17.04. Grazie
