### ISSUE TITLE
Aggiornare DCATAP_IT

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#11]
Sul github di Geosolutions che ha sviluppato il plugin per il DCAT_AP_IT ci sono tante patch rispetto alla versione inclusa nel docker. sono anche patch fondamentali per la creazione del catalog.rdf

Dovreste aggiornare la versione del plugin inclusa nel docker.

**Comment by giux78** [comment]
Si Geosolutions ci sta supportando nello sviluppo e dovrebbero a breve allineare anche questo docker con il loro lavoro.

**Comment by piersoft** [comment]
ho provato a importare la versione nuova del dcatap_it dal github di geosolutions dentro un docker che aveva già dei dataset. sembrava tutto ok e le modifiche del backend dei dataset erano state recepite (autore opzionale con il + ect).
ma cliccando poi la singola risorsa dava server error. ho rimesso la versione precedente del plugin dcatap_it e ha ripreso tutto. provo appena posso su un docker nuovo senza dataset e vi dico.

**Comment by giux78** [comment]
grazie mille piersoft tienici aggiornati credo che rilasceremo il docker nuovo per la fine del mese.

**Comment by giux78** [comment]
@piersoft abbiamo mergiato con le modfiche di geosolutions. a me sembra non funzionare. se vuoi provare e darci feedback. apro pure un  issue.

**Comment by piersoft** [comment]
anche a me non funziona..



Il giorno 16 febbraio 2018 22:38, Alessandro Ercolani <
notifications@github.com> ha scritto:

**Comment by giux78** [comment]
Ok abbiamo aggiornato. adesso dovrebbe funzionare.
