### ISSUE TITLE
./init.sh

### ISSUE THREAD

**Issue by giux78** [italia/dati-ckan-docker#14]
init lancia un docker exec ma il nome del container sembra sbaggliato. @randomorder @etj forse quel comando non lo devo nemmeno lanciare? E se voglio entrare come admin su ckan user e pass?

**Comment by randomorder** [comment]
Ciao @giux78 
Si, e' un errore della documentazione perche' il nome del container dipende da come lo si lancia.
Ho modificato il README sul nostro fork con il comando corretto da usare:
https://github.com/geosolutions-it/dati-ckan-docker/commit/7d3b4762988824d86271c5e2dece4aa6f712f50f

> identify the name of the CKAN Container and run the following command: `docker exec  -ti <ckan> /ckan-init.sh`
> where `<ckan>` is the name of the container as per `docker ps` command output

quello script ( /ckan-init.sh ) che si trova all' interno del container, tra le altre cose, setta usename e password dell' utente amministratore

**Comment by giux78** [comment]
Ok grazie mille sembra funzionare. @randomorder fai pure una pull request cosi mergiamo. grazie mille.

**Comment by giux78** [comment]
@randomorder piu veloce della luce.

**Comment by randomorder** [comment]
https://github.com/italia/dati-ckan-docker/pull/15

Grazie @giux78
