### ISSUE TITLE
Campo Titolare non compilabile

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#18]
ho provato ad usare questa nuova versione del docker con il nuovo aggiornamento del plugin dcatap_it.

nel backend il campo Titolare (name e IPA) non è valorizzabile. manca proprio lo spazio dove inserire i dati.

<img width="416" alt="schermata 2018-02-25 alle 12 32 58" src="https://user-images.githubusercontent.com/6083002/36641166-74d29788-1a2b-11e8-9dbe-bcf037497582.png">

**Comment by giux78** [comment]
@randomorder @etj potete darci un occhio? grazie mille

**Comment by etj** [comment]
Come discusso in [questa issue](https://github.com/geosolutions-it/ckanext-dcatapit/issues/72) il campo titolare non è direttamente editabile, ma è preso dall'organizzazione proprietaria del dataset.

**Comment by piersoft** [comment]
non è corretto. 
Supponiamo un Comune che voglia pubblicare un dato, la chi titolarietà non è propria.
Qualità dell’aria (Arpa Regionale.. che ad oggi non hanno catalogo dati aperti), piuttosto che partecipate (Trasporti, Energia etc).
Deve essere editabile.

Piersoft
Inviato da iPhone

**Comment by etj** [comment]
In quel caso il Comune sarà il publisher e l'Arpa sarà il rightsholder (e avrà una sua organizzazione all'interno del ckan pubblicato dal Comune).
