### ISSUE TITLE
errore link RDF ini ckan-init.sh

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#19]
le ontologie territoriali e delle licenze hanno un link modificato sulla repo AGID delle ontologie e ckan-init.sh va in errore.

tale errore diventa poi Server Error in tutti i dataset perchè non viene caricato più il menu a tendina nella risorsa per la licenza. 
Correggere i link:

wget "https://github.com/italia/daf-ontologie-vocabolari-controllati/raw/c998fb435ee77082880b6f98e230ec5273a09e6d/VocabolariControllati/ClassificazioneTerritorio/Istat-Classificazione-08-Territorio.rdf" -O "/tmp/Istat-Classificazione-08-Territorio.rdf"
paster --plugin=ckanext-dcatapit vocabulary load --filename "/tmp/Istat-Classificazione-08-Territorio.rdf" --name regions --config "$CKAN_INI_PATH"

wget "https://raw.githubusercontent.com/italia/daf-ontologie-vocabolari-controllati/50738e7527b44af9c25d75b955f67f927553f51f/VocabolariControllati/Licenze/Licenze.rdf" \
-O "/tmp/Licenze.rdf"
paster --plugin=ckanext-dcatapit vocabulary load --filename "/tmp/Licenze.rdf" --name licenses --config "$CKAN_INI_PATH"

**Comment by giorgialodi** [comment]
Ciao @piersoft ma cambiando quindi il path tutto poi ti funziona? Hai provato o hai solo identificato il problema? Perché se hai cambiato opportunamente, perché non fai proprio una PR? Noi poi la valutiamo e se tutto è ok, facciamo merge.

**Comment by piersoft** [comment]
si funziona tutto.

ho fatto una PR la e sbagliata perchè punta all’ultima versione delle ontologie che NON funzionano nello script.
Mentre qui nella issue vi ho messo il link alla versione delle ontologie funzionanti (in pratica le precedenti)

Piersoft
Inviato da iPhone

**Comment by piersoft** [comment]
ok ho aperto la PR
