### ISSUE TITLE
Accesso da IP e non da localhost

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#2]
provando a inserire l'ip della macchina per poter accedere via browser, non accetta connessioni.

ho notato che Apache , Ngix non vengono installati nel docker. 
E' normale?

**Comment by dgreco** [comment]
si, e' il normale comportamento di Docker. Tieni conto che questo progetto server solo per fare test, per questo non serve un'installazione completa, con reverse proxy ecc.

**Comment by piersoft** [comment]
Tenendo conto del fatto che ora il progetto può essere usato in produzione (come da discussione nella issue #4 ) rilancio la domanda.

Da localhost a ip esterno, cosa conviene modificare nell'installazione del docker?

thanks
