### ISSUE TITLE
harvest da rdf non corretto

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#22]
sto importando a causa spostamento server e provider, il catalogo dati.comune.francavillafontana.br.it

Quando lo realizzai non usai il docker ma l'installazione classica con il plug in dcatap_it.

Ora il nuovo server ha l'ultima versione del Docker e quando facco l'harvesting usando la soluzione rdf (quindi puntando al catalog.rdf del sito si sopra) le importazioni non sono corrette:
1) il campo Titolare non appare nel Dataset (esce N/A) ma è presente nel nuovo rdf del portale harvestante. non potendolo cambiare (è un campo bloccato  nella nuova versione del plugin) non so come fare
2) tutte le frequenze sono importate come "unknow" quando nell'rdf originale hanno correttamente il valore
3) i temi sono importati come ECON o Dati Provvisori e non con i valori corretti.

Sto aggiustando a mano tutti i dataset purtroppo.

<img width="743" alt="schermata 2018-04-07 alle 07 59 59" src="https://user-images.githubusercontent.com/6083002/38453868-fc47919a-3a5c-11e8-8ac2-b61a73506f0a.png">

<img width="821" alt="schermata 2018-04-07 alle 08 00 54" src="https://user-images.githubusercontent.com/6083002/38453867-f896b9f4-3a5c-11e8-90bd-a91e874cffb2.png">

**Comment by giorgialodi** [comment]
@piersoft grazie per la segnalazione. Ci sono ancora issue aperti e non abbiamo rilasciato la nuova versione del docker con alcune modifiche. Bene tenere sotto osservazione anche gli issue e le PR qui https://github.com/geosolutions-it/ckanext-dcatapit. 
Quando dici che il titolare è un campo bloccato nel nuovo plugin non è del tutto vero. C'è un modo diverso, rispetto al passato, di specificarlo. Il modo diverso è stato necessario perché nel profilo il titolare è un oggetto organizzazione. Si deve quindi creare un'organizzazione all'interno di CKAN. Sulla base di questo tuo commento comunque abbiamo apportato delle modifiche per cercare di guidare meglio l'utente in fase di inserimento. Nel repo che ho puntato sopra si trovano tutte le interazioni e le scelte fatte. 
Invece investighiamo meglio le anomalie sul catalog.rdf per quanto riguarda frequenze e temi. Grazie.

**Comment by jenkin** [comment]
Chiusa per inattività.
