### ISSUE TITLE
Problemi preview della risorsa

### ISSUE THREAD

**Issue by eslu** [italia/dati-ckan-docker#26]
Salve a tutti,
ho installato il pacchetto docker di CKAN in due server diversi.
In entrambi riscontro un problema nel preview delle risorse.
Una volta inserita una risorsa (es. un file csv), se provo a visualizzare il preview, riscontro un "Internal server error".

![ckan-1](https://user-images.githubusercontent.com/39831176/40841864-3cec5026-65ac-11e8-8a7c-5048785e50d6.png)

![ckan-2](https://user-images.githubusercontent.com/39831176/40841854-34632bb4-65ac-11e8-95d2-748ad8f40735.png)

Analizzando il log, vedo un warning:
WARNI [ckan.lib.maintain] Function _resource_preview() in module ckan.controllers.package has been deprecated and will be removed in a later release of ckan. Resource preview is deprecated. Please use the new resource views

È possibile che abbia mancato oppure che debba cambiare qualcosa nella configurazione del ckan.ini?

Grazie

**Comment by giorgialodi** [comment]
Ciao @eslu, chiediamo immensamente scusa per il ritardo nella risposta. A me personalmente il tuo messaggio era completamente sfuggito. Hai ancora i problemi che dicevi o sei riuscito a superarli? Se li hai ancora, posso chiederti come hai costruito il tutto? Hai seguito i passi del readme di questo repo? Grazie e scusa ancora.

**Comment by eslu** [comment]
Ciao Giorgia.
non ti preoccupare, immagino sia complicato stare dietro a tutto.
In realtà questo problema si verificava con una versione presente diversi mesi fa sul repo, ho fatto installazioni successive per altri progetti seguendo sempre il readme e non ho più riscontrato il problema.
Se hai un'idea di quale possa essere il problema però te ne sarei grato, perché su un server ho ancora quella versione installata e se potessi fare qualche prova renderei quell'installazione stabile.

Grazie

**Comment by giorgialodi** [comment]
Ciao @eslu,
abbiamo fatto delle prove con l'ultimissima versione dell'estensione DCAT-AP_IT installata e 1) con dataset che provengono da harvesting l'anteprima ci funziona;  2) con dataset creati da noi via web form, come sembra essere il tuo caso, il tuo problema non si presenta :( 
Tuttavia volevo dirti che stiamo facendo degli aggiornamenti e ancora altri test. Forse meglio, anche rispetto a quello che mi dici, utilizzare versioni più recenti. 
Una curiosità  per capire  l'utilizzo del docker: i progetti a cui ti riferisci sono presso PA o presso privati? Grazie

**Comment by eslu** [comment]
Ciao Giorgia,
si tratta di un progetto per la PA.
In realtà il problema non è bloccante in quanto il CKAN è utilizzato come repository e viene interrogato solo tramite API (che funzionano correttamente), quindi il frontend non è utilizzato in maniera ufficiale. Avrei voluto risolvere il problema in modo da utilizzare il frontend di ckan per eventuali verifiche interne, ma il problema è aggirabile perché riesco comunque a fare il download del file.
Comunque con installazioni successive effettivamente anche io non ho più riscontrato il problema.
Grazie
