### ISSUE TITLE
Inserimento file publiccode.yml

### ISSUE THREAD

**Issue by libremente** [italia/dati-ckan-docker#30]
Ciao, apro questa issue per intavolare la discussione relativa alla pubblicazione del software contenuto in questo repo all'interno del nuovo catalogo in Developers Italia in ottemperanza al CAD e alla [nuove LG su acquisizione e riuso](https://lg-acquisizione-e-riuso-software-per-la-pa.readthedocs.io/it/latest/acquisizione-software/introduzione-e-contesto-normativo.html).
Per far ciò, bisogna realizzare un file `publiccode.yml` da inserire nella root del repo nel branch master contenente le informazioni che serviranno al crawler per popolare la entry nel catalogo, seguendo [queste specifiche](https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/).
Aprirò a breve una PR dove vi coinvolgerò come reviewer per rivedere/integrare informazioni che potrebbero sfuggirmi. 
Grazie molte :wink: 
@jenkin

**Comment by jenkin** [comment]
Ho sistemato la descrizione, mancano tre elementi:

* `legal.repoOwner`
* il file AUTHORS indicato in `legal.authorsFile`
* uno o più maintainers in `maintenance.contacts`

**Comment by libremente** [comment]
#31 Inserisce il nuovo `publiccode.yml`. 
Grazie @jenkin, chiudo.
