### ISSUE TITLE
Un dubbio sull'obiettivo di questo container

### ISSUE THREAD

**Issue by aborruso** [italia/dati-ckan-docker#4]
Buongiorno,
ho un dubbio "stupido": in #2 @dgreco scrive "Tieni conto che questo progetto serve solo per fare test".

Questo container è pensato per un comune che, avendo al suo interno un sysadmin con competenze di docker e CKAN, voglia mettere in **produzione** il proprio portale? O è solo per fare test?

Grazie

**Comment by dgreco** [comment]
Non e' stupido per niente ;) l'intento principale per noi era di poter testare una serie di applicazioni che usano ckan. Penso che possa eventualmente essere usato in produzione introducendo la persistenza basata su volumi docker. Con adeguate competenze non vedo problemi, d'altra parte docker e' usato ampiamente in produzione.

**Comment by aborruso** [comment]
@dgreco se è tagliato anche per il caso d'uso che ho indicato, lo scriverei anche nel README.

I comuni italiani che espongono dati sono qualche centinaia su 8000. Una quantità preoccupante.

Dirgli "da oggi, con adeguate competenze, avete a disposizione una modalità per essere operativi in modo semplice e standard" secondo me sarebbe una gran cosa e un bell'obiettivo di AgID e Team.
Che ne pensi/ate?

Grazie

**Comment by rasky** [comment]
Fatto, abbiamo chiarito semplicemente che ad oggi non ci sono esperienze ancora di esecuzione in ambiente di produzione, ma che l'obiettivo è sicuramente meritevole :)

**Comment by aborruso** [comment]
@rasky grazie. 

Sono d'accordo che sia meritevole, ma sopratutto mi fa piacere che adesso sia etichettato come "it can provide a good base for running a production service".

Io cambierei 

>  It has been currently used only in testing environments but we think it can provide a good base for running a production service.

in

> It has been currently used only in testing environments but it can provide a good base for running a production service.

Saluti
