### ISSUE TITLE
Errori interni nella creazione di un DataSet

### ISSUE THREAD

**Issue by rossellaCeglie** [italia/dati-ckan-docker#40]
Installato il Docker.
Apparentemente sembra Ok, l'ho configurato e compaiono le info, il logo ecc.
Se provo ad aggiungere un dataset, però, vengono visualizzati degli errori, fra cui uno in particolare: "Estensione temporale - errore interno: lista / <type 'dict'>"
Se provo però a cliccare su "aggiungi estensione temporale" il pulsante è disabilitato così come alcuni altri (cerchiati in giallo). C'è quacosa che non è andato per il verso giusto?

[v1.pdf](https://github.com/italia/dati-ckan-docker/files/3350694/v1.pdf)

**Comment by jenkin** [comment]
Ciao, dal pdf che hai allegato mi sembra che tu non stia usando l'ultima versione disponibile sulla branch master di questo repository.

Se sei nel dubbio, ti consiglio di stoppare i container che hai in esecuzione (`docker-compose down` nella tua cartella di progetto) e ripetere la procedura dall'inizio seguendo i 6 step indicati nel [README](https://github.com/italia/dati-ckan-docker/blob/master/README.md).

Qui ti allego anche un pdf con gli screenshot dei vari passi di creazione di un nuovo dataset. Nota che quando clicchi su "Nuovo dataset" e inserisci le prime informazioni, in fondo alla pagina ci sono due pulsanti: "Classificazioni" e "Prossimo: Aggiungi Dati". Tu devi prima di tutto cliccare su "Classificazioni" e poi sui pulsanti successivi per completare la procedura di inserimento di tutti i metadati (come da screenshot). Solo al termine clicchi su "Prossimo: Aggiungi Dati" e carichi i dati veri e propri (ultima pagina del pdf).

[dati-ckan-docker_add-dataset-steps.pdf](https://github.com/italia/dati-ckan-docker/files/3353883/dati-ckan-docker_add-dataset-steps.pdf)

Quando fatto, facci sapere, grazie!

**Comment by rossellaCeglie** [comment]
Niente. Ho fatto come da te suggerito ma il risultato è uguale: ci sono dei link disabilitati, contrassegnato dal simbolo "+", e fra questi quello collegato a "aggiungi estensione temporale", da cui  l'errore.
:(

**Comment by piersoft** [comment]
Ho controllato anche io. ho lo stesso bug di @rossellaCeglie . I tasti "+" nel newdataset non sono più cliccabili ed essendoci campi obbligatori, è un bug bloccante per l'inserimento di nuovi dataset. 
Sembra quasi un problema di css cmq. nella consolle javascript non si vedono errori

**Comment by piersoft** [comment]
ho commentato in base.html (templates):
  {#<body{% block bodytag %} data-site-root="{{ h.url_for('/', locale='default', qualified=true) }}" data-locale-roo etc

e ho messo semplicemente `<body>` e funziona tutto implementando "tabs"=True nel ckan.ini. anzi quasi tutto perchè ci sono ancora cose "strane" nel sorgente:

 
```
--
<link rel="alternate" type="text/n3" href="http://xxxxx:5000/?hostog.n3?host="/>
  | <link rel="alternate" type="text/ttl" href="http://xxxxxx:5000/?hostog.ttl?host="/>
  | <link rel="alternate" type="application/rdf+xml" href="http://xxxxxxx:5000/?hostog.xml?host="/>
  | <link rel="alternate" type="application/ld+json" href="http://xxxxxxx:5000/?hostog.jsonld?host="/>
  |  

```
questo crea problemi con le anteprime

**Comment by jenkin** [comment]
@rossellaCeglie abbiamo risolto con @piersoft _dietro le quinte_ , a quanto pare la procedura **opzionale** di harvesting automatico di fonti dati esterne crea problemi, ma appunto è **opzionale** e nel vostro caso d'uso non utile.

Provvediamo ad aggiornare il README per chiarire meglio questo punto.
