### ISSUE TITLE
harvesting nuova versione alert

### ISSUE THREAD

**Issue by piersoft** [italia/dati-ckan-docker#42]
nella versione attuale del docker, se si installa la parte "deprecata" e opzionale dell'harvesting, ho avuto alcuni problemi.
In particolare viene creato un link strano per ogni risorsa che cambia url in dominio/?hosted/nomerisorsa  al posto del classico dominio/dataset/risorsa

**Comment by jenkin** [comment]
@piersoft puoi verificare se il problema persiste dopo l'ultimo aggiornamento?

**Comment by piersoft** [comment]
ora funziona tutto

Piersoft
Inviato da iPhone
