### ISSUE TITLE
versione 2.6.7 ckan docker

### ISSUE THREAD

**Issue by nicolapiva** [italia/dati-ckan-docker#43]
Ho provato ad installare il nuovo ckan versione 2.6.7 su docker. Ho un problema legato all'inserimento dei tag finali (Localized Tag Name). Inserisco i valori, salvo ma non si memorizzano. Sapete dirmi qualcosa?
Grazie.

**Comment by jenkin** [comment]
Scusa il ritardo, grazie della segnalazione, verifichiamo quanto prima. Hai altre informazioni a riguardo, per esempio eventuali log al momento del salvataggio?

**Comment by nicolapiva** [comment]
Ho fatto dei test per ora e ho cancellato la macchina virtuale che ho utilizzato, per cui non ho i log da mandare. L'unica cosa che posso dire è che quando ho guardato i log non c'era niente di legato a questo mancato salvataggio. Grazie.

**Comment by jenkin** [comment]
Duplicata di #51
