### ISSUE TITLE
Problema con build ckan

### ISSUE THREAD

**Issue by LME1209** [italia/dati-ckan-docker#61]
Salve a tutti,

nel fare la build del ckan con comando "docker-compose -f docker-compose.yml -f docker.compose.build.yml build" si blocca con questo errore:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==21.0', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
ERROR: Service 'ckan' failed to build: The command '/bin/sh -c pip install pytz diagnostics' returned a non-zero code: 1

qualcuno sta riscontrando lo stesso problema?

**Comment by eslu** [comment]
Salve,
ho riscontrato lo stesso problema ed ho risolto inserendo nel Dockerfile l'upgrade di pip ad una specifica versione

`RUN pip install --upgrade pip==20.3.3`

al posto di 

`RUN pip install --upgrade pip`

Probabilmente l'ultima versione di pip causa l'errore.
Con la versione 20.3.3 non ho avuto problemi, ma non escludo che ci siano altre versioni funzionanti. 

Saluti

**Comment by LME1209** [comment]
Grazie mille, l'ho risolto anche io esattamente in questo modo.

Saluti

**Comment by LME1209** [comment]
Aggiungo che c'è una pull request attiva con questa modifica ma di cui non è stata fatta la merge.

https://github.com/italia/ckan-it/pull/62

Saluti
